name: Run Tests

on:
  push:
    branches:
      - main # You can specify the branch you want to trigger on push
  pull_request:
    branches:
      - main # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest # This runs the job on an Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use the version of Node.js your project needs

      - name: Install dependencies
        run: npm install # This installs your project dependencies

      - name: Run tests
        run: npm test # This runs the tests using Jest
